### ISSUE TITLE
Is it possible to have dynamic Text in maskElement

### ISSUE THREAD

**Issue by im-aditya** [react-native-community/react-native-masked-view#19] opened 2019-08-13 14:16 UTC
If I change the text in the given example from 'Basic Mask' to something which changes with the state for example: 

`<Text>{`${this.state.remainingTime} Seconds`}</Text>`

And at some interval I change this state, then the mask's text should change. But its not happening. Is this not supported or is that a bug ?

Thanks

**Comment by jordangrant** [comment] 2019-10-29 09:06
SAME

**Comment by FonDorn** [comment] 2019-11-04 18:27
@im-aditya it is posible. Can you provide full code or you can check this example:
```
export default class App extends React.Component {
  state = {
    text: 'Start'
  };

  remainingTime = 0;

  componentDidMount() {
    setInterval(
      () => this.setState({ text: `${++this.remainingTime} Seconds` }),
      1000
    );
  }

  render() {
    return (
      <MaskedView
        style={{ flex: 1, flexDirection: 'row', height: '100%' }}
        maskElement={
          <View
            style={{
              // Transparent background because mask is based off alpha channel.
              backgroundColor: 'transparent',
              flex: 1,
              justifyContent: 'center',
              alignItems: 'center'
            }}
          >
            <Text
              style={{
                fontSize: 60,
                color: 'black',
                fontWeight: 'bold'
              }}
            >
              {this.state.text}
            </Text>
          </View>
        }
      >
        {/* Shows behind the mask, you can put anything here, such as an image */}
        <View style={{ flex: 1, height: '100%', backgroundColor: '#324376' }} />
        <View style={{ flex: 1, height: '100%', backgroundColor: '#F5DD90' }} />
        <View style={{ flex: 1, height: '100%', backgroundColor: '#F76C5E' }} />
        <View style={{ flex: 1, height: '100%', backgroundColor: '#e1e1e1' }} />
      </MaskedView>
    );
  }
}
```

**Comment by jordangrant** [comment] 2019-11-04 20:35
@FonDorn doesn’t work on Android only btw

**Comment by FonDorn** [comment] 2019-11-04 20:48
@jordangrant  oh yes, you are right

**Comment by shubhamkakkar** [comment] 2020-01-10 20:02
I am not sure about native android, but I just made a sample code on EXPO snack, ran it on android and it is working with maskedElem text state-dependent

https://github.com/shubhamkakkar/reanimated-practie/blob/master/toggleAnimationMaskedView.js

**Comment by Sakarisson** [comment] 2020-04-28 09:29
Seems like this issue has been resolved in the newest release, FYI :)

**Comment by kulyk** [comment] 2020-05-09 22:30
Confirm, the issue is fixed 👐

**Closed** 2020-05-10 05:50 UTC
Labels: Platform: Android, help wanted
